config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  namespace :users do 
    resources :users
  end 

  root 'homes#index'
  resources :homes
  resources :job_categorys
  namespace :admin do 
    resources :jobs
    get 'my_jobs', :to => 'jobs#my_jobs'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable,
         :registerable,
         :recoverable, 
         :rememberable,
         :validatable,
         :trackable,
         :confirmable 
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @job_categorys = JobCategory.all
    super
  end

  # POST /resource/sign_in
  def create
    @job_categorys = JobCategory.all
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :ransack_search, only: %i[index edit]

  def index
    @my_jobs = Job.where(job_post_id: current_user.id)
  end

  def edit
    @my_jobs = Job.where(job_post_id: current_user.id)
    @job = Job.find(params[:id])
  end

  def condition_for_edit
    @my_jobs = true
  end

  private
  def job_params
    params.require(:job).permit(:title, :job_category_id, :employment_type, :location_type, :salary, :link_to_apply,
     :description, :max_positions, :qualification, :job_category_name, :job_post_id)
  end

  def ransack_search
    @q = Job.ransack(params[:q])
    @jobs = @q.result(distint: true).page(params[:page])
    @job_categorys = JobCategory.all
  end
end

app/views/users/users/edit.html.erb
<!-- Form for Job Input  -->

<div class="container w-50 border border-1 shadow">
  <div class="row p-4 justify-content-center">
    <%= form_with model: [:admin, @job] do |form| %>

    <%= form.hidden_field :job_post_id, value: current_user.id %>

     <div>
       <%= form.label :status %> :<br>
       <%= form.select :status, ['Public','Archived'], selected:'Public' %>
     </div>
 
    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :title , class:"form-label" %><br>
      <%= form.text_field :title , class:"form-control p-2" %>
    </div>

    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :Job_category_id, class:"form-label" %><br>
      <%= form.select :job_category_id, options_for_select(JobCategory.pluck(:name, :id)), {prompt: 'Select Jobcategory'}, { class: 'form-select form-select-lg rounded-0'} %>
    </div>


    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :Employment_type, class:"form-label" %><br>
      <%= form.select :employment_type, options_for_select(Job::EMPLOYMENT_TYPE),{prompt: 'Select Employment_type'},{ class: 'form-control p-2 form-select form-select-lg rounded-0'}%>
    </div>

    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :qualification, class:"form-label" %><br>
      <%= form.select :qualification, options_for_select(Job::QUALIFICATION),{prompt: 'Select qualification'},{ class: 'form-control p-2 form-select form-select-lg rounded-0'}%>
    </div>

    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :location_type, class:"form-label" %><br>
      <%= form.select :location_type, options_for_select(Job::LOCATION_TYPE),{prompt: 'Select Location'},{ class: 'form-control p-2 form-select form-select-lg rounded-0'}%>
    </div>


    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :salary, class:"form-label" %><br>
      <%= form.select :salary, options_for_select(Job::SALARY),{prompt: 'Select Salary Range'},{ class: 'form-control p-2 form-select form-select-lg rounded-0'}%>
    </div>

    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :link_to_apply, class:"form-label" %><br>
      <%= form.text_field :link_to_apply, class:"form-control p-2"%>
    </div>

    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :max_positions, class:"form-label" %><br>
      <%= form.text_field :max_positions, class:"form-control p-2" %>
    </div>

    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :Upload_company_image , class:"form-label" %><br>
      <%= form.file_field :company_image  %>
    </div>

    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.label :description, class:"form-label" %><br>
      <%= form.text_area :description,:cols => 10, :rows => 5, class:"form-control p-2" %>
    </div>

    <div class="pt-2 col col-12 mb-3 form-control-lg">
      <%= form.submit class:'btn btn-danger btn-lg' %>
    </div>
    <% end %>
  </div>
</div>
<!-- Form for Job Input -->

app/views/users/users/index.html.erb
<div class="container">
  <div class="row mb-5 p-2 ">
    <% @my_jobs.each do |job| %>
      <div class="col-4 ">
        <div class="card shadow mb-5 ">
          <div class="card-img-top">
            <% if job.company_image.attached? %>
              <%= image_tag job.company_image, class:"img-fluid  "%>
            <% else %>
              <%= image_tag("https://images.unsplash.com/photo-1574958269340-fa927503f3dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1948&q=80A", class:"img-fluid card-img-top ")%>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"> 
             <li class=" text-danger
             "><%= job.status %></li>
            </h5>
            <p class="card-text">
              <li class="mb-2"><span class="h5">Title - </span> <%= job.title %> </li>
              <li class="mb-2"><span class="h5">link_to_apply - </span><%= link_to job.link_to_apply,job.link_to_apply, :target => '_blank' %></li>
              <li class="mb-2"><span class="h5">job_post_id - </span><%= job.job_post_id %></li>
              <li class="mb-2"><span class="h5" >Job Category - </span><%= job.job_category.name %></li>
              <li class="mb-2"><span class="h5">Employment Type - </span><%= job.employment_type %></li>
              <li class="mb-2"><span class="h5">Qualification - </span><%= job.qualification %></li>
              <li class="mb-2"><span class="h5">Location - </span><%= job.location_type %></li>
              <li class="mb-2"><span class="h5">Salary - </span><%= job.salary %></li>
              <li class="mb-2"><span class="h5">Max. Positions - </span><%= job.max_positions %></li>
              <li class="mb-2"><span class="h5">Description - </span><%= job.description %></li>
            </p>
            <% if @my_jobs %>
              <%= link_to 'Edit', edit_users_user_path(job) , class:"btn btn-secondary" %>
              <%= link_to 'Delete', admin_job_path(job), data: {turbo_method: :delete, turbo_confirm:"Are you sure ?"}, class:"btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
 </div>
</div>
<%= paginate @jobs %>